### ISSUE TITLE
Want to take a look at the code

### ISSUE THREAD

**Issue by asaf050** [stevebauman/maintenance-app#3]
Hey,
I can't find in this repository any Models, Controllers or Routes so I can't understand where the code is.

In addition, if there any online demo version it will be great!
I really appreciate your work, Thank you very much!

**Comment by stevebauman** [comment]
Hi @asaf050, the main repository for maintenance code is in the [maintenance](http://www.github.com/stevebauman/maintenance) repository, this package installs that upon installation. This repository is just for an easy install, which comes with configurations and migrations pre-published.
